# Generated by Django 5.2.17 on 2026-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('address', models.CharField(max_length=200, verbose_name='dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['name'],
            },
        ),
    ]
